version: "3.9"
services:
    database-mysql:
        image: mysql:8.0
        container_name: test-db-mysql
        volumes:
            - ./volumes/mysql-data:/var/lib/mysql
            - ./volumes/mysql-logs:/var/log/mysql
        networks:
            - frontend-database
            - mysql-phpmyadmin
        ports:
            - 3306:3306
        env_file:
            - ./media/environment.env
        restart: always
    db-admin-phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        container_name: test-dbadmin-phpmyadmin
        volumes:
            - /sessions
        networks:
            - mysql-phpmyadmin
        ports:
            - 82:80
        env_file:
            - ./media/environment.env
        depends_on:
            - database-mysql
    frontend-angular:
        build: ./frontend
        container_name: test-frontend-angular
        ports:
            - 80:80
        restart: always
        depends_on:
            - database-mysql
    frontend-wordpress:
        image: wordpress:5.7
        container_name: test-frontend-wordpress
        volumes:
            - ./volumes/wordpress:/var/www/html
        networks:
            - frontend-database
        ports:
            - 81:80
        env_file:
            - ./media/environment.env
        restart: always
        depends_on:
            - database-mysql
networks:
    frontend-database: {}
    mysql-phpmyadmin: {}
